name: 🚀 Push to GitHub Server

on:
  push:
    branches:
      - main

jobs:
  test:
    name: ✅ Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🛠 Install dependencies
        run: composer install --no-dev --prefer-dist

      - name: 🧪 Run tests
        run: php artisan test

  push:
    name: 🚀 Push Code to GitHub
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📤 Push to GitHub
        run: git push origin main